// Copyright 2024 The Nakama Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: events/events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventEnvelope is the top-level wrapper for all events flowing from Nakama to PamOps via Redis Streams.
type EventEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID v4 unique event identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unix milliseconds when the event was created.
	TimestampMs int64 `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Nakama node name that originated the event (from config.GetName()).
	SourceNode string `protobuf:"bytes,3,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	// Dot-separated event type (e.g., "realm.player_joined", "audit.security.ban").
	EventType string `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Schema version for forward compatibility. Starts at 1.
	Version int32 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EventEnvelope_RealmEvent
	//	*EventEnvelope_AuditEvent
	Payload       isEventEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_events_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventEnvelope) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *EventEnvelope) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *EventEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventEnvelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EventEnvelope) GetPayload() isEventEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventEnvelope) GetRealmEvent() *RealmEvent {
	if x != nil {
		if x, ok := x.Payload.(*EventEnvelope_RealmEvent); ok {
			return x.RealmEvent
		}
	}
	return nil
}

func (x *EventEnvelope) GetAuditEvent() *AuditEvent {
	if x != nil {
		if x, ok := x.Payload.(*EventEnvelope_AuditEvent); ok {
			return x.AuditEvent
		}
	}
	return nil
}

type isEventEnvelope_Payload interface {
	isEventEnvelope_Payload()
}

type EventEnvelope_RealmEvent struct {
	RealmEvent *RealmEvent `protobuf:"bytes,10,opt,name=realm_event,json=realmEvent,proto3,oneof"`
}

type EventEnvelope_AuditEvent struct {
	AuditEvent *AuditEvent `protobuf:"bytes,11,opt,name=audit_event,json=auditEvent,proto3,oneof"`
}

func (*EventEnvelope_RealmEvent) isEventEnvelope_Payload() {}

func (*EventEnvelope_AuditEvent) isEventEnvelope_Payload() {}

// RealmEvent carries realm lifecycle and player movement events.
type RealmEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID of the realm this event pertains to.
	RealmId string `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	// Action type: "created", "deleted", "status_changed", "player_joined", "player_left", "metadata_changed".
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	// User ID of the actor who triggered the event. Empty for system-initiated events.
	ActorUserId string `protobuf:"bytes,3,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	// Additional context as key-value pairs.
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealmEvent) Reset() {
	*x = RealmEvent{}
	mi := &file_events_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealmEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealmEvent) ProtoMessage() {}

func (x *RealmEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealmEvent.ProtoReflect.Descriptor instead.
func (*RealmEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{1}
}

func (x *RealmEvent) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *RealmEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RealmEvent) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *RealmEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// AuditEvent carries security, admin, and gameplay audit trail entries.
type AuditEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event category: "security", "admin", "gameplay".
	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	// Specific action (e.g., "ban", "unban", "role_change", "config_update").
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	// User ID of the affected user.
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// User ID of the actor who performed the action.
	ActorId string `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// Realm context if applicable (empty for global actions).
	RealmId string `protobuf:"bytes,5,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	// JSON-encoded details for the audit entry.
	Details       string `protobuf:"bytes,6,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_events_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{2}
}

func (x *AuditEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditEvent) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *AuditEvent) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// CacheInvalidationPayload carries cross-system cache invalidation signals.
type CacheInvalidationPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific cache keys to invalidate.
	CacheKeys []string `protobuf:"bytes,1,rep,name=cache_keys,json=cacheKeys,proto3" json:"cache_keys,omitempty"`
	// Key prefixes to invalidate (all keys matching prefix).
	CachePrefixes []string `protobuf:"bytes,2,rep,name=cache_prefixes,json=cachePrefixes,proto3" json:"cache_prefixes,omitempty"`
	// Human-readable reason for the invalidation.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheInvalidationPayload) Reset() {
	*x = CacheInvalidationPayload{}
	mi := &file_events_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheInvalidationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheInvalidationPayload) ProtoMessage() {}

func (x *CacheInvalidationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_events_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheInvalidationPayload.ProtoReflect.Descriptor instead.
func (*CacheInvalidationPayload) Descriptor() ([]byte, []int) {
	return file_events_events_proto_rawDescGZIP(), []int{3}
}

func (x *CacheInvalidationPayload) GetCacheKeys() []string {
	if x != nil {
		return x.CacheKeys
	}
	return nil
}

func (x *CacheInvalidationPayload) GetCachePrefixes() []string {
	if x != nil {
		return x.CachePrefixes
	}
	return nil
}

func (x *CacheInvalidationPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_events_events_proto protoreflect.FileDescriptor

const file_events_events_proto_rawDesc = "" +
	"\n" +
	"\x13events/events.proto\x12\rnakama.events\"\xa3\x02\n" +
	"\rEventEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x1f\n" +
	"\vsource_node\x18\x03 \x01(\tR\n" +
	"sourceNode\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x12<\n" +
	"\vrealm_event\x18\n" +
	" \x01(\v2\x19.nakama.events.RealmEventH\x00R\n" +
	"realmEvent\x12<\n" +
	"\vaudit_event\x18\v \x01(\v2\x19.nakama.events.AuditEventH\x00R\n" +
	"auditEventB\t\n" +
	"\apayload\"\xe5\x01\n" +
	"\n" +
	"RealmEvent\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\tR\arealmId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\"\n" +
	"\ractor_user_id\x18\x03 \x01(\tR\vactorUserId\x12C\n" +
	"\bmetadata\x18\x04 \x03(\v2'.nakama.events.RealmEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x01\n" +
	"\n" +
	"AuditEvent\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\tR\aactorId\x12\x19\n" +
	"\brealm_id\x18\x05 \x01(\tR\arealmId\x12\x18\n" +
	"\adetails\x18\x06 \x01(\tR\adetails\"x\n" +
	"\x18CacheInvalidationPayload\x12\x1d\n" +
	"\n" +
	"cache_keys\x18\x01 \x03(\tR\tcacheKeys\x12%\n" +
	"\x0ecache_prefixes\x18\x02 \x03(\tR\rcachePrefixes\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reasonB,Z*github.com/heroiclabs/nakama-common/eventsb\x06proto3"

var (
	file_events_events_proto_rawDescOnce sync.Once
	file_events_events_proto_rawDescData []byte
)

func file_events_events_proto_rawDescGZIP() []byte {
	file_events_events_proto_rawDescOnce.Do(func() {
		file_events_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_events_proto_rawDesc), len(file_events_events_proto_rawDesc)))
	})
	return file_events_events_proto_rawDescData
}

var file_events_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_events_events_proto_goTypes = []any{
	(*EventEnvelope)(nil),            // 0: nakama.events.EventEnvelope
	(*RealmEvent)(nil),               // 1: nakama.events.RealmEvent
	(*AuditEvent)(nil),               // 2: nakama.events.AuditEvent
	(*CacheInvalidationPayload)(nil), // 3: nakama.events.CacheInvalidationPayload
	nil,                              // 4: nakama.events.RealmEvent.MetadataEntry
}
var file_events_events_proto_depIdxs = []int32{
	1, // 0: nakama.events.EventEnvelope.realm_event:type_name -> nakama.events.RealmEvent
	2, // 1: nakama.events.EventEnvelope.audit_event:type_name -> nakama.events.AuditEvent
	4, // 2: nakama.events.RealmEvent.metadata:type_name -> nakama.events.RealmEvent.MetadataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_events_events_proto_init() }
func file_events_events_proto_init() {
	if File_events_events_proto != nil {
		return
	}
	file_events_events_proto_msgTypes[0].OneofWrappers = []any{
		(*EventEnvelope_RealmEvent)(nil),
		(*EventEnvelope_AuditEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_events_proto_rawDesc), len(file_events_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_events_proto_goTypes,
		DependencyIndexes: file_events_events_proto_depIdxs,
		MessageInfos:      file_events_events_proto_msgTypes,
	}.Build()
	File_events_events_proto = out.File
	file_events_events_proto_goTypes = nil
	file_events_events_proto_depIdxs = nil
}
